[package]
name = "international-park-ssi"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = {version = "0.12.7", features = ["json"]}
rocket = { version = "0.5.1", features = ["json"] }
serde_json = "1.0.127"
tokio = { version = "1.40.0", features = ["full"] }
